#!/bin/bash

set -e

npm install
go install github.com/raviqqe/gherkin2markdown@latest
gherkin2markdown features/ docs/
echo ">> Feature file to markdown ok"
cp -f CHANGELOG.md CONTRIBUTING.md DEVELOPMENT.md README.md docs/
echo ">> Copy ok"
node script/docsify-auto-sidebar.js -d docs
echo ">> Sidebar ok"
npx docsify serve docs/
